version: '3'
services:

  flight-services:
    build:
      context: ./flight
    ports:
      - 8080:8080
    links:
      - redis

  plane-services:
    build:
      context: ./plane
    ports:
      - 8081:8081

  redis:
    image: redis
    ports:
      - 6379:6379